//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programmingDataProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers_Suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers_Suppliers()
        {
            this.Clients = new HashSet<Client>();
            this.Permissions = new HashSet<Permission>();
            this.Storage_cust_sup = new HashSet<Storage_cust_sup>();
        }
    
        public string ID { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string BirthDate { get; set; }
        public Nullable<int> phone { get; set; }
        public Nullable<int> mobile { get; set; }
        public Nullable<int> fax { get; set; }
        public string Mail { get; set; }
        public string website { get; set; }
        public string Location { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permission> Permissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_cust_sup> Storage_cust_sup { get; set; }
    }
}
