//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programmingDataProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emloyee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emloyee()
        {
            this.Storages = new HashSet<Storage>();
        }
    
        public string ID_Emp { get; set; }
        public string name { get; set; }
        public int Password { get; set; }
        public Nullable<int> phone { get; set; }
        public Nullable<int> mobile { get; set; }
        public string Mail { get; set; }
        public string Location { get; set; }
        public Nullable<int> Storage_ID_emp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage> Storages { get; set; }
    }
}
