//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programmingDataProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Company_ProjectEntities : DbContext
    {
        public Company_ProjectEntities()
            : base("name=Company_ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Customers_Suppliers> Customers_Suppliers { get; set; }
        public virtual DbSet<Emloyee> Emloyees { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Storage> Storages { get; set; }
        public virtual DbSet<Storage_cust_sup> Storage_cust_sup { get; set; }
        public virtual DbSet<Storage_item> Storage_item { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Transport_items> Transport_items { get; set; }
    }
}
