//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programmingDataProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int permission_ID { get; set; }
        public string typePermission { get; set; }
        public int item_id { get; set; }
        public string Date_permission { get; set; }
        public int stroage_id { get; set; }
        public Nullable<int> amount_item { get; set; }
        public string name_id { get; set; }
        public string expireDate { get; set; }
        public string Comment { get; set; }
    
        public virtual Customers_Suppliers Customers_Suppliers { get; set; }
        public virtual item item { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
