//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programmingDataProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage_item
    {
        public int Storage_ID { get; set; }
        public int Item_ID { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual item item { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
