//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programmingDataProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage_cust_sup
    {
        public int Storage_id { get; set; }
        public string cust_sup_id { get; set; }
        public string date { get; set; }
    
        public virtual Customers_Suppliers Customers_Suppliers { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
