//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programmingDataProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport_items
    {
        public int Transaction_ID { get; set; }
        public string supplier_Name { get; set; }
        public string Product_Name { get; set; }
        public string From_Storage { get; set; }
        public string To_Storage { get; set; }
        public string amount { get; set; }
        public string TransactionDate { get; set; }
    }
}
